security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        js_router:
            pattern: ^/(js\/routing)
            security: false
        main:
            pattern: ^/
            switch_user:
                provider:   fos_userbundle
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                #default_target_path: /
                use_referer: true
            logout:
              path:   /logout
              target: /login
            anonymous:    true

    access_control:
        - { path: ^/Inventory/RegularInventoryLookup$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/CategoryLookup$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_thrace-datagrid/data/W3viewCategoryList$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_thrace-datagrid/data/W3viewItemsList$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
